ALTER TABLE plants
  DROP COLUMN IF EXISTS names VARCHAR(120)[],
  DROP COLUMN IF EXISTS scientific_name VARCHAR(120),
  DROP COLUMN IF EXISTS sowing TEXT,
  DROP COLUMN IF EXISTS light INTEGER,
  DROP COLUMN IF EXISTS days_to_harvest INTEGER,
  DROP COLUMN IF EXISTS row_spacing INTEGER,
  DROP COLUMN IF EXISTS spread INTEGER,
  DROP COLUMN IF EXISTS fruit_months TEXT,
  DROP COLUMN IF EXISTS native VARCHAR(120)[],
  DROP COLUMN IF EXISTS images JSONB,
  DROP COLUMN IF EXISTS treflePath  VARCHAR(80),
  DROP COLUMN IF EXISTS gbifSpeciesKey INTEGER;